# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RzpueDc45RpLFRIGc4W86axpluGk9Zbn
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from google.colab import files
uploaded = files.upload()  # Choose your CSV file from your Mac

import pandas as pd
df = pd.read_csv('Diwali Sales Data.csv', encoding='unicode_escape')
df.head()

df.info()

df.drop(['Status','unnamed1'] , axis=1,inplace=True)

df.isnull()

df.isnull().sum()

df.dropna(inplace=True)

df['Amount'] = df['Amount'].astype('int')

df['Amount'].dtypes

df.columns

df.rename(columns={'Marital_Status':'Shaadi'})

df.describe()
df[['Age','Orders',"Amount"]].describe()

#EDA



ax = sns.countplot(x='Gender',data=df)

for bars in ax.containers:
    ax.bar_label(bars)

#Group by on the basis of Gender:
sales_gender= df.groupby(['Gender'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)

print(sales_gender)

ax = sns.countplot(data= df, x = 'Age Group',hue= 'Gender' )

for bars in ax.containers:
    ax.bar_label(bars)

sales_age= df.groupby(['Age Group'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)

print(sales_age)

ax = sns.barplot(data=sales_age,x= 'Age Group',y='Amount')

sales_state= df.groupby(['State'],as_index=False)['Orders'].sum().sort_values(by='Orders',ascending=False).head(10)

print(sales_state)

ax = sns.barplot(data=sales_state,x= 'State',y='Orders', hue = 'State')

for bars in ax.containers:
    ax.bar_label(bars)

sns.set(rc={'figure.figsize':(15,10)})

#*From above graphs we can see that most of the orders are from Uttar Pradesh, Maharashtra and Karnataka respectively sales/amount is from UP, Karnataka and then Maharashtra*

ax = sns.countplot(x='Marital_Status',data=df)

for bars in ax.containers:
    ax.bar_label(bars)

x = df.groupby(['Marital_Status','Gender'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)

print(x)

ax = sns.barplot(data=x,x='Marital_Status',y='Amount',hue='Gender')

#*From above graphs we can see that most of the buyers are murried (women) and they have high purchasing power*

Occ_Orders= df.groupby(['Occupation'],as_index=False)['Orders'].sum().sort_values(by='Orders',ascending=False)

ax = sns.barplot(data=Occ_Orders, x='Occupation', y='Orders')

for bars in ax.containers:
    ax.bar_label(bars)

Pro_Orders= df.groupby(['Product_Category'],as_index=False)['Orders'].sum().sort_values(by='Orders',ascending=False).head(10)

#Top Selling product
ax  = sns.barplot(data=Pro_Orders, x='Product_Category', y='Orders')

for bars in ax.containers:
    ax.bar_label(bars)
sns.set(rc={'figure.figsize':(20,5)})

"""Conclusion -

Married women age group 26-35 yrs from UP, Maharastra and Karnataka working in IT, Healthcare and Aviation are more likely to buy products from Food
Clothing and Electronics category """

